//Tutoring(id*, email, classCode, className, price, rating, availability)
let tutorsList = [
  {
    id: "0",
    firstName: "John",
    lastName: "Doe",
    email: "JohnDoe@gmail.com",
    classCode: ["COP3502", "CNT4007", "THE3000"],
    price: "$15 per hour",
    rating: 3.0,
    availability: ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"],
  },
  {
    id: "1",
    firstName: "Lisa",
    lastName: "Mona",
    email: "LisaMona@yahoo.com",
    classCode: ["COP3503", "WIS2432", "DML3002"],
    price: "$20 per hour",
    rating: 5.0,
    availability: ["Monday", "Wednesday", "Friday"],
  },
  {
    id: "2",
    firstName: "Bill",
    lastName: "Russell",
    email: "BillRussell@yahoo.com",
    classCode: ["GIS3245", "GEO3530", "GEO3000"],
    price: "$10 per hour",
    rating: 2.3,
    availability: ["Tuesday", "Thursday"],
  },
  {
    id: "3",
    firstName: "Sue",
    lastName: "Bird",
    email: "SueBird@gmail.com",
    classCode: [
      "SPM4104",
      "SPM4154",
      "MAN3025",
      "SPM4004",
      "SPM4954",
      "MAN4825",
      "SPM7104",
      "SPM6154",
      "MAN5025",
    ],
    price: "$18 per hour",
    rating: 4.7,
    availability: ["Monday", "Tuesday", "Wednesday", "Thursday"],
  },
  {
    id: "4",
    firstName: "Allen",
    lastName: "Iverson",
    email: "AllenIverson@gmail.com",
    classCode: ["EEL3033", "DIR3600", "MAN3025"],
    price: "$36 per hour",
    rating: 2.1,
    availability: ["Monday", "Tuesday", "Thursday", "Friday"],
  },
];

export default tutorsList;
