name: Cypress Run

on:
  push:
    branches: [ bleeding ]
  pull_request:
    branches: [ bleeding ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Go Run InitDB
        working-directory: backend
        run: go run ./cmd/initdb/main.go

      - name: Go Run Server
        working-directory: backend
        run: go run ./cmd/server/main.go

      - name: Cypress Run
        uses: cypress-io/github-action@v2
        with:
          working-directory: frontend
          start: npm start
          wait-on: 'http://localhost:8080'
